### ISSUE TITLE
städte

### ISSUE THREAD

**Issue by Iranox** [Iranox/Hexenverfolgung#5]
[{"_id":"Zschopau","quantity":1},{"_id":"Oederan","quantity":6},{"_id":"Gahlenz","quantity":1},{"_id":"ober-Strawalde","quantity":2},{"_id":"Neustadt\/Orla","quantity":1},{"_id":"Bautzen","quantity":2},{"_id":"Viernau","quantity":2},{"_id":"Belzig","quantity":3},{"_id":"Benshausen","quantity":21},{"_id":"Sch\u00f6nerstadt","quantity":3},{"_id":"Endorf","quantity":1},{"_id":"Felgeleben","quantity":2},{"_id":"Dornbach","quantity":1},{"_id":"Breitenhagen","quantity":3},{"_id":"Sonneberg","quantity":1},{"_id":"Ebertshausen","quantity":1},{"_id":"Barby","quantity":2},{"_id":"Augustusburg","quantity":2},{"_id":"Erlenberg","quantity":1},{"_id":"Annaburg","quantity":2},{"_id":"Sorn\u00dfig","quantity":2},{"_id":"Borstendorf","quantity":1},{"_id":"Niemegk","quantity":2}]

**Comment by Doldenberg** [comment]
Könntet ihr eventuell gleich eine Vorlage in Data legen, in welchem Format ihr die Geodaten wollt, damit sie gleich verwertbar sind? Bzw. auch einfach nur sagen, ob zum Beispiel eine .csv mit Spalte ID, Längengrad, Breitengrad okay ist, dann würde ich es einfach so machen?

**Comment by Iranox** [comment]
dachte eher an die 
Spalten Ort, Längengrag, Breitengrad

**Comment by Iranox** [comment]
habe eine vorlage reingestellt.
